# Generated by Django 4.0.6 on 2022-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_publication_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3)),
                ('weight', models.FloatField()),
                ('length', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('vacinated', models.BooleanField()),
                ('dewormed', models.BooleanField()),
                ('sterilized', models.BooleanField()),
            ],
            options={
                'db_table': 'Pet',
            },
        ),
    ]
